.PHONY: build push

DOCKER_IMAGE_VERSION=1.0.7
DOCKER_LASTEST_VERSION=lastest
DOCKER_IMAGE_NAME=j0nl1/nexus:$(DOCKER_IMAGE_VERSION)
DOCKER_IMAGE_NAME_LASTEST=j0nl1/nexus:$(DOCKER_LASTEST_VERSION)

build:
	docker build . -t $(DOCKER_IMAGE_NAME) .
	docker build . -t $(DOCKER_LASTEST_VERSION)

push:
	docker push $(DOCKER_IMAGE_NAME)
	docker push $(DOCKER_IMAGE_NAME_LASTEST)